name: 'cfn-guard-scan-action'
description: 'A composite action to run CFN-Guard scan and annotate results'
inputs:
  templates_folder:
    description: 'Path to the CloudFormation templates'
    required: false
    default: './templates'
permissions:
  pull-requests: write
  security-events: write
  actions: read
  contents: read
runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Validate cloudformation against the guard rules
      id: validate
      uses: aws-cloudformation/cloudformation-guard@action-v0.0.5
      with:
        rules: ${{ github.action_path }}/rules
        data: ${{ inputs.templates_folder }}
        checkout: false
        create-review: true
    - name: Convert cfn-guard results to SARIF
      if: ${{ failure() && steps.validate.conclusion == 'failure' }}
      run: |
        mkdir -p results
        echo '${{ steps.validate.outputs.result }}' > results/cfn-guard-results.sarif
        echo "Printing SARIF results:"
        cat results/cfn-guard-results.sarif
      shell: bash
    - name: Annotate SARIF results
      if: ${{ failure() && steps.validate.conclusion == 'failure' }}
      uses: SirYwell/sarif-annotator@v0.2.1
      with:
        report-path: results/cfn-guard-results.sarif
        source: qodana
