name: "cfn-guard-scan-action"
description: "A composite action to run CFN-Guard scan and annotate results"
inputs:
  data:
    description: "Path to the CloudFormation templates"
    required: true
permissions:
  pull-requests: write
  security-events: write
  actions: read
  contents: read
runs:
  using: "composite"
  steps:
    - name: List files in the rules folder for debugging
      run: |
        echo "Listing files in the rules folder:"
        ls -al "cfnguard-action/rules"
      shell: bash

    - name: Validate CloudFormation against the guard rules
      id: validate
      uses: aws-cloudformation/cloudformation-guard@action-v0.0.5
      with:
        rules: "cfnguard-action/rules"
        data: ${{ inputs.data }}
        checkout: false
        create-review: true
        debug: true
